### ISSUE TITLE
Error when logging on to the server

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Universe-Viewer-Dev#2]
Decided to describe the mistakes that appeared during the login process from the client to the server. The first is
Can't find inventory item db5a4e5f-9da3-44c8-992d-1181c5795498 for Skin, setting to default
Can't find inventory item 6969c7cc-f72f-4a76-a19b-c293cce8ce4f for Hair, setting to default
Can't find inventory item 7999702b-b291-48f9-8903-c91dfb828408 for Eyes, setting to default
Can't find inventory item 566cb59e-ef60-41d7-bfa6-e0f293fbea40 for Shirt, setting to default
these errors client videt server and close.

As I understand it you need to fix something in the file llagentwearables

Translated using Google translator

**Comment by CaseyraeStarfinder** [comment]
Greetings

This is not a viewer bug.  This usually means there is an asset missing from the asset server in the grid your logging into.  In which case there is nothing that would need to be adjusted in llAgentWearables.  Additionally if your using the source code from a different development team for your viewer there is not much in the way of support we can give you for the code in that viewer.  

If the problem persists (in most cases this should not occur), please report the bug to the grid operators or determine the grid architecture being used and report it as a bug on the appropriate issue tracker.

Best Regards,

Caseyrae Starfinder
Governing Body Vice Chair (Europe)
Core Developer
Viewer Developer Work Group Leader
Viewer Development Work Group
Second Galaxy Development Team
Email: caseyrae@secondgalaxy.com

**Comment by LifeGold** [comment]
The basis was taken viewer second life 4.1.2 you have here 4.0.9. Today is your viewer who posted here, this error is and in that and in other.

**Comment by CaseyraeStarfinder** [comment]
Greetings,

The viewer is not yet fully compatible with the Virtual Universe architecture just yet.  Some features may work properly while others might not.  The default avatar that comes with Virtual Universe is known to come as grey however in most cases doing a rebake will solve this.  However the missing asset is not a viewer bug but a grid server bug which should be reported to the correct issue tracker should the issue continue occurring.  

I would encourage your users to use Firestorm viewer for the moment while we continue sorting through the work still needing to be done prior to the upcoming beta release.

We also strongly recommend grid owners and operators using the Virtual Universe architecture to test the viewer code and open issues on our tracker to request features and report bugs in the viewer to help us make sure we get them fixed prior to the beta release.

Best Regards,

Caseyrae Starfinder
Governing Body Vice Chair (Europe)
Core Developer
Viewer Developer Work Group Leader
Viewer Development Work Group
Second Galaxy Development Team
Email: caseyrae@secondgalaxy.com

**Comment by LifeGold** [comment]
I'll wait then, since we need a year of the servers never used clients fire and other teams, but only your own. Appropriately customers where there is mention of other games or pleasure teams is unacceptable as it is against the rules of our server.

**Comment by CaseyraeStarfinder** [comment]
Greetings

For a grid to be successful it is not really recommended to limit users to your official viewer.  There are many people who will prefer a different viewer such as the Firestorm Viewer (opensim supported version).  However we do recommend blocking viewers based on the Viewer Version 1.23 and Version 2.0 (Snowglobe) versions as the Second Galaxy Development Team has voted to drop support in both the Virtual Universe Architecture and the proprietary GalaxyGrid Architecture for these viewers.  Viewers known to use version 1.23 or version 2.0 code bases are Imprudence Viewer and Singularity Viewer.  

Also you can submit pull requests for code you want to contribute to the viewer.

Best Regards,
Caseyrae Starfinder
Governing Body Vice Chair (Europe)
Core Developer
Viewer Developer Work Group Leader
Viewer Development Work Group
Second Galaxy Development Team
Email: caseyrae@secondgalaxy.com

**Comment by LifeGold** [comment]
When you compile a client that you have in the repository here's what
http://prntscr.com/d37rul

**Comment by LifeGold** [comment]
If interested I can share the latest source Second Life Bento 5.0.0

**Comment by CaseyraeStarfinder** [comment]
Greetings,

I am going to assume that your trying to build the bento client from Linden Labs here.  If so that issue shouldn't impact our viewer code here.  Although I do know the Doxygen error comes up in their official viewer repository as well.

Adding bento would need to be opened on our issue tracker as a feature request.

Closing this issue ticket as the initial compile question has been answered.

Best Regards,
Caseyrae Starfinder
Governing Body Vice Chair (Europe)
Core Developer
Viewer Developer Work Group Leader
Viewer Development Work Group
Second Galaxy Development Team
Email: caseyrae@secondgalaxy.com

**Comment by LifeGold** [comment]
This particular client was building No, the folder is called Bento where it was installed.
