### ISSUE TITLE
Add Grid

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Universe-Viewer-Dev#3]
Hi, this customer has collected, as you add your grid?

**Comment by CaseyraeStarfinder** [comment]
Greetings,

I am not sure what you are really asking here.  If your requesting your grid info be added to the grids list then you will need to submit it as a feature request with the login url etc.  

Keep in mind this code is now outdated in this repository and will be changing later today in favor of code approved by the Core Developers of the development team.

Best Regards,
Caseyrae Starfinder
Governing Body Vice Chair (Europe)
Core Developer
Viewer Developer Work Group Leader
Viewer Development Work Group
Second Galaxy Development Team
Email: caseyrae@secondgalaxy.com
